### PR TITLE
Support @Priority ordering of loaded classes.

### PR DESCRIPTION
**Pull request by sjoerdtalsma**
As described in #8, this is needed when multiple `TracerConverters` are registered.
The `@Priority` annotation can then provide a prioritized ordering of the converters.

Priority is applied by natural ordering (smallest number first), followed by objects without `@Priority` annotations. Objects with a negative priority are applied after priority-less objects.

### CODE REVIEW

**Comment by sjoerdtalsma** [comment]
@objectiser PTAL

**Review by objectiser — APPROVED** [review]
Although initial PR comment talked about property for `TracerConverter` - but I assume once that PR is merged, then property will be added for that aswell?

**Comment by sjoerdtalsma** [comment]
@objectiser Actually, since `@Priority` is required for the `TracerConverter`, I think _this_ PR should merge before [the converter one](https://github.com/opentracing-contrib/java-tracerresolver/pull/8).

**Comment by sjoerdtalsma** [comment]
@objectiser Sorry, I think I misunderstood.
The answer is **yes** the `TracerConverter` most definitely should be prioritized as well.

**Pull request merged**
